# Generated by Django 5.2.4 on 2025-08-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="uploaded_file",
            field=models.FileField(blank=True, null=True, upload_to="file/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="uploaded_img",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
