# Generated by Django 5.2.4 on 2025-08-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0002_alter_shop_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="price",
            field=models.IntegerField(),
        ),
    ]
